### ISSUE TITLE
Update Breaking dependencies

### ISSUE THREAD

**Issue by rafaelmaeuer** [swrlab/ard-eventhub#250]
Migrate and check its working
- [x] dd-trace: 1.7.0 -> 2.7.0
- [x] dotenv: 14.3.2 -> 16.0.0
- [x] google-auth-library: 7.14.1 -> 8.0.2

Change source of package
- [x] undici-wrapper frytg -> node-utils

Requires Rust-Toolkit in Docker
- [x] node-crc: 1.3.2 -> 2.0.11

Requires ES6-Module
- [ ] ansi-regex: 5.0.1 -> 6.0.1
- [ ] strip-ansi: 6.0.1 -> 7.0.1

**Comment by frytg** [comment]
`dotenv` is no problem, `dd-trace` just needs an update to the enabled env (needs to be false for test, since true is the default)

https://github.com/swrlab/ard-eventhub/blob/3453c8f91707c1f2078681e76e650495ea79902d/src/utils/tracer/index.js#L9
