### ISSUE TITLE
Add examples for each element type

### ISSUE THREAD

**Issue by saerdnaer** [swrlab/ard-eventhub#3]
* [x] music
* [x] news
* [x] live
* [x] weather
* [x] traffic
* [ ] audio
* [ ] commercial
* [ ] jingle

**Comment by frytg** [comment]
Is this still an open issue @saerdnaer and what would be the required documentation for this?

**Comment by saerdnaer** [comment]
@frytg Could you provide a link to the current examples?

**Comment by rafaelmaeuer** [comment]
Examples for Music, News, Live, Weather and Traffic added with: https://github.com/swrlab/ard-eventhub/pull/73/
