### ISSUE TITLE
Check schema validation on boot

### ISSUE THREAD

**Issue by rafaelmaeuer** [swrlab/ard-eventhub#433]
Lately the following error comes upon boot:

`formats as an array is deprecated. Use object instead https://ajv.js.org/options.html#formats`

Might have todo with express-openapi-validator update to [v5.0.0](https://github.com/cdimascio/express-openapi-validator/releases/tag/v5.0.0)

**Comment by rafaelmaeuer** [comment]
Created a new Issue:
- https://github.com/cdimascio/express-openapi-validator/issues/826

**Comment by frytg** [comment]
Resolved in v1.5.0 https://github.com/swrlab/ard-eventhub/pull/453 with https://github.com/swrlab/ard-eventhub/commit/313921daab3652d167f12d3952b61af9c00fe03d
