### ISSUE TITLE
Remove error rejection from response to avoid leaking possibly sensitive details

### ISSUE THREAD

**Issue by frytg** [swrlab/ard-eventhub#494]
https://github.com/swrlab/ard-eventhub/blob/33369ee31827b90fb824d765c6e2b4022cea0c28/src/ingest/auth/login/post.js#L26

(plus more endpoints)

**Comment by rafaelmaeuer** [comment]
- only give error-code or general error-message back
- prevent firebase-sensitive information ind req/res
- check for other endpoints which handle the same way
