### ISSUE TITLE
extend `role` list for `contributors`

### ISSUE THREAD

**Issue by saerdnaer** [swrlab/ard-eventhub#699]
Bisher haben wir im Eventhub im entsprechenden `role`-Enum ja nur folgende vier Werte:

- artist, composer, performer, author:

https://github.com/swrlab/ard-eventhub/blob/ae345c5946bb825df225c027a8d1f43ff030ff5f/openapi.json#L941-L950

Können wir da noch weitere Werte hinzufügen? Also z.B.

```
choir         > Chor
conductor     > Dirigent
ensemble      > Ensemble
leader        > Einstudierung
member        > Mitglieder
orchestra     > Orchester
producer      > Produktion
soloist       > Solist
engineer      > Tontechnik
```

Sofern es dafür natürlich schon einen passenden Standard gibt auf den man sich beziehen kann – um so besser...

**Comment by frytg** [comment]
@saerdnaer Es gibt verschiedene Standards, aber die haben dann ja auch wieder ihre eigenen Lizenzen...

Damit es ähnlich zu den vorigen ist, müssten wir ja vermutlich alle auch klein schreiben.
Verständlich finde ich die alle durchaus. Nur bei `member` fände ich den Unterschied zu `performer` relativ klein, oder? Statt `soundengineer` könnte man auch überlegen nur `engineer` zu nehmen.

**Comment by saerdnaer** [comment]
Ja, der Unterschied zwischen `member`, `artist`, `performer` usw. ist aktuell eher unklar und bräuchte wohl langfristig noch etwas mehr definition – aber die jetzt im Pull-Request gewählte Variante finde ich eigentlich ganz gut...
