### ISSUE TITLE
Update/Improve OpenAPI specification

### ISSUE THREAD

**Issue by rafaelmaeuer** [swrlab/ard-eventhub#93]
- [ ] Is the field `"id": "urn:ard:permanent-livestream:49267f7d67be180d"` still valid in request body example of /events?
- [ ] Is it possible to alter `eventV1ResBody` scheme in /events (next) so request body example matches `"event": "de.ard.eventhub.v1.radio.track.next"` instead of `"event": "de.ard.eventhub.v1.radio.track.playing"`?
- [ ] Is it possible to alter `eventV1ResBody` scheme in /events response body examples to add fields like `name` and `created`?

**Comment by rafaelmaeuer** [comment]
@frytg as a kind reminder to have a look at my changes on ARD-Eventhub OpenAPI-Docs: https://github.com/swrlab/ard-eventhub/pull/94/files (openapi.yaml)

**Comment by frytg** [comment]
@rafaelmaeuer is this still up-to-date? It seems like we made some changes a year ago, but nothing else was really required?

**Comment by rafaelmaeuer** [comment]
I guess yes, I remember this addressed some not-up-to-date fields

**Comment by saerdnaer** [comment]
Can you provide an example which shows the issue in more detail?

**Comment by frytg** [comment]
closing this for now, might need some future follow up if actual problems occur
